### ISSUE TITLE
Support for sending null values to bacnet

### ISSUE THREAD

**Issue by plucpel** [openhab/org.openhab.binding.bacnet#2]
Currently null values sent on openhab as well as received from bacnet are not interpreted converted as expected. This lead to gaps in cases where null values have special meaning.

Formalizing issue from the [OpenHab community thread](https://community.openhab.org/t/bacnet-binding-question/45637/11) - such feature will allow to relinquish from priority array. As of `1.13.0` release each and every item on OH side might specify write priority and null values are necessary to let some controllers work properly.

Would like to see if it is possible to support relinquishing the value set at a certain priority level so that the relinquish default (or whatever controlling logic other than OH) can take over.

**Comment by splatch** [comment]
As discussed - we introduced support for sending null values to bacnet and handling of these on inbound path as well. Let me know if that will help.

**Comment by plucpel** [comment]
@splatch Consolidating feedback from the openhab forum here :

I tried sending UnDefType.null through the binding and got the following error :

`java.lang.IllegalArgumentException: Could not parse number value out of string UnDefType.NULL. Make sure value is parsable float
	at org.openhab.binding.bacnet.internal.BacNetValueConverter.encodeFloat(BacNetValueConverter.java:146) ~[191:org.openhab.binding.bacnet:1.13.0.201901072357]
	at org.openhab.binding.bacnet.internal.BacNetValueConverter.openHabTypeToBacNetValue(BacNetValueConverter.java:123) ~[191:org.openhab.binding.bacnet:1.13.0.201901072357]
	at org.openhab.binding.bacnet.internal.BacNetBinding$2.toBacNet(BacNetBinding.java:127) ~[191:org.openhab.binding.bacnet:1.13.0.201901072357]
	at org.openhab.binding.bacnet.internal.BacNetBinding$2.toBacNet(BacNetBinding.java:1) ~[191:org.openhab.binding.bacnet:1.13.0.201901072357]
	at org.code_house.bacnet4j.wrapper.ip.BacNetIpClient.getBacNetValue(BacNetIpClient.java:226) ~[191:org.openhab.binding.bacnet:1.13.0.201901072357]
	at org.code_house.bacnet4j.wrapper.ip.BacNetIpClient.setPropertyValue(BacNetIpClient.java:241) ~[191:org.openhab.binding.bacnet:1.13.0.201901072357]
	at org.openhab.binding.bacnet.internal.queue.WritePropertyTask.run(WritePropertyTask.java:62) [191:org.openhab.binding.bacnet:1.13.0.201901072357]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`
